GET http://localhost:5000/products

###
GET http://localhost:5000/products/5


###

POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "armande",
    "price": 1000
}


###

PATCH http://localhost:5000/products/2
Content-Type: application/json

{
    "name": "ruperto",
    "price": 250

}


###

DELETE http://localhost:5000/products/5



